name: Sync Papers and Components to Website

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout awesome-papers-for-rag (Source Repo)
        uses: actions/checkout@v3 # 这是您的源仓库

      # --- 关键点：使用 actions/checkout 克隆目标仓库，并明确传递令牌 ---
      - name: Checkout target repo (gomate-community.github.io)
        uses: actions/checkout@v3
        with:
          repository: gomate-community/gomate-community.github.io # 明确指定目标仓库
          path: gomate-community.github.io # 克隆到此目
          # Optional: Configure author for commits made from this checkout
          user.email: "fanyixing111@hotmail.com" # 确保是您GitHub账户的邮箱
          user.name: "faneshion" # 确保是您GitHub账户的用户名
          token: ${{ secrets.GH_TOKEN }}

      - name: Sync files
        run: |
          # 复制文件：从当前源仓库目录复制到克隆的目标仓库目录
          cp README.md gomate-community.github.io/_pages/awesome-papers-for-rag/README.md
          cp rewriter.md gomate-community.github.io/_pages/awesome-papers-for-rag/rewriter.md
          cp ranker.md gomate-community.github.io/_pages/awesome-papers-for-rag/ranker.md
          cp mediation.md gomate-community.github.io/_pages/awesome-papers-for-rag/mediation.md
          cp generator.md gomate-community.github.io/_pages/awesome-papers-for-rag/generator.md
          cp validator.md gomate-community.github.io/_pages/awesome-papers-for-rag/validator.md
          cp evaluation.md gomate-community.github.io/_pages/awesome-papers-for-rag/evaluation.md
          cp images/rag1.png gomate-community.github.io/assets/rag1.png

      - name: Commit & push changes
        run: |
          cd gomate-community.github.io # 进入目标仓库的目录
          git add .

          # 检查是否有需要提交的更改
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            # 确保在当前仓库内设置了提交者信息
            git config user.email "fanyixing111@hotmail.com"
            git config user.name "faneshion"

            git commit -m "Sync _pages/awesome-papers-for-rag from awesome-papers-for-rag [auto]"
            # 由于前面的 actions/checkout 已经用 token 配置了远程，这里直接 push 即可
            git push origin main
            echo "Successfully synced files from awesome-papers-for-rag"
          fi
